### PR TITLE
Fixed scss for optimized view

### PR DESCRIPTION
**Pull request by halith-smh**
I looks like an scrollbar is viewed on laptop screen which seems not good and also change the footer padding properly...

Thank you..

### CODE REVIEW

**Comment by scffs** [comment]
Hello! 

if we use `overflow: hidden;` on body we can't scroll page in other screens, so it's not a clean solution

**Comment by halith-smh** [comment]
In the Home page their is only one section ?

The scrollbar disturb the home section hence it seems optimized

**Comment by halith-smh** [comment]
image

**Comment by scffs** [comment]
> I just changed only in the home page scss file and i have checked no possibility to change the scroll behavior of other pages..

but you're using `body` selector 

image

**Comment by halith-smh** [comment]
image

**Comment by scffs** [comment]
`padding: 16px` is too small 

image

**Comment by scffs** [comment]
Looks like fixed

**Review by scffs — APPROVED** [review]

**Comment by halith-smh** [comment]
/portfolio/news

> I'll merge it but if u have some ideas u can tell me about them here or create new PR
> 
> Thanks for PR

Look like in the page: /portfolio/news : we can change the skeleton loader skin , i mean it need some changes

**Comment by scffs** [comment]
> Look like in the page: /portfolio/news : we can change the skeleton loader skin , i mean it need some changes

Maybe it needs but looks fine, if you wanna make it better - create new PR please

**Comment by halith-smh** [comment]
Ok, I'll

**Pull request merged**
